### PR TITLE
Adding design select and a check for stale github branches

### PR DESCRIPTION
**Pull request by Waschnick**
- Added custom.css to be overwritten in projects
- Added a second design with a selector
- Added a new StaleBranches check for Github

### CODE REVIEW

**Comment by ulich** [comment]
Could you please add a section to the README how to use the column layout and the custom styles?

**Comment by Waschnick** [comment]
> Could you please add a section to the README how to use the column layout and the custom styles?

Done

**Comment by ulich** [comment]
i just realized that the column layout doesnt support comments anymore, is that correct?

**Comment by Waschnick** [comment]
Well we can have multiple layouts, but at Egoditor they didn't want the comments. May we re-add them to the column based design and I add it for egoditor in custom.css

**Comment by ulich** [comment]
or another idea: we add the ability to make comments configurable and support them in any layout

**Comment by Waschnick** [comment]
I like that idea, maybe that's even the better way of doing it.

**Pull request merged**
